### ISSUE TITLE
/maps/edit/village-market route not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1004]
Hi @cesswairimu ! After #777 it seems this route isn't working for some reason: 

http://mapknitter-stable.laboratoriopublico.org/maps/edit/village-market

I get a 404: 

`That page does not exist.`

Would you have a moment to see what's up? 

Thank you!

**Comment by cesswairimu** [comment]
Hey @jywarren I mentioned the issue here https://github.com/publiclab/mapknitter/pull/777#issuecomment-530037451 maybe u didn't get a chance to see it and I had opened a PR for the fix #1003  but @sashadev-sky already included the fix in #1001 , so I closed mine. This should be working fine after Sasha's PR is merged. Thanks

**Comment by jywarren** [comment]
Oops, thanks for pointing that out!

**Comment by jywarren** [comment]
Perfect, fixed in #1001 Thanks!
