### ISSUE TITLE
Redesign UI for about page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1113]
We moved a couple things around on the about page. This is how it  looks like, currently

![screencapture-localhost-3000-about-2019-11-10-22_49_39](https://user-images.githubusercontent.com/17081074/68549749-ba4dc900-040c-11ea-9e91-6b706f2f4378.png)

 There are a few improvements that could be done to it. Suggestions...
- [ ] The image is so stretched out(could use some styling or maybe we get another image? Is the positioning right?
- [ ] We could add some more content on the about page and maybe some links to the wiki on how mapknitter was used
- [ ] We could add more helpful statistics on the the statistics section..maybe how many maps we have in total and images?

-----------------------------------------
Suggestions are definitely welcome..feel free to edit/comment below. Thanks

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI

**Comment by Uzay-G** [comment]
Hey @cesswairimu! I am excited to work on this issue and will create a pull request when I am done :smile:

**Comment by Uzay-G** [comment]
@cesswairimu for the redesign I am kinda confused because the actual mapknitter website's design looks like this:
![Screenshot from 2019-12-11 18-28-37](https://user-images.githubusercontent.com/52892257/70644916-3c1b5700-1c44-11ea-9325-546de8c5345f.png)

Whereas the localhost about page is like this:
![local](https://user-images.githubusercontent.com/52892257/70644942-49d0dc80-1c44-11ea-9a14-18852b92c1be.png)

Is there a specific deploy branch I should edit instead of the main one to do the redesign? Thanks

**Comment by cesswairimu** [comment]
Hey @Uzay-G, awesome yeah please do :tada: ..glad to have you work on this...Great catch on the icons thanks. On the branch we recommend you create a new branch off of main and do your changes there..let me know if you need any help in create the branch. Thanks again

**Comment by Uzay-G** [comment]
Thanks @cesswairimu! So I should create a branch and then make a pr to merge with main?

**Comment by cesswairimu** [comment]
Yes please

**Comment by Uzay-G** [comment]
Hey @cesswairimu, this is what I have for now:
![about-map1](https://user-images.githubusercontent.com/52892257/70652234-8e637480-1c52-11ea-958a-8e44e823998c.png)
![about-map2](https://user-images.githubusercontent.com/52892257/70652235-8efc0b00-1c52-11ea-9f12-a62449882cad.png)
![about-map3](https://user-images.githubusercontent.com/52892257/70652236-8efc0b00-1c52-11ea-8c6c-d9d15c40e47d.png)
 
It's all responsive but I am still gonna improve some things.
What do you think?
Note: The cut between the images is just because they are separate images.

**Comment by Uzay-G** [comment]
I also edited the footer from this:
![before-footer](https://user-images.githubusercontent.com/52892257/70655767-1cdaf480-1c59-11ea-97f9-4be40d9d9e9c.png)
to this:
![after-footer](https://user-images.githubusercontent.com/52892257/70655766-1c425e00-1c59-11ea-8a53-65f6c189ccd8.png)

I'd really appreciate your feedback @cesswairimu. I'm being a bit adventurous with my choices but I understand if that's not what you're looking for and you can just tell me.

**Comment by cesswairimu** [comment]
Love the uniformity...Great job

**Comment by SidharthBansal** [comment]
Cess you are doing a great job. My inbox is full of your name. :-))

**Comment by cesswairimu** [comment]
Thanks @SidharthBansal :blush:
