### ISSUE TITLE
Compatibility with Leaflet.DistortableImage 0.8.7

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1124]
I'm getting this error after upgrading LDI to 0.8.7:

```
Map.self-4f3676dc77ea2a47adb308e7e998bd6deaf8f6a9400070cbbaaf6412acd01e7c.js?body=1:162 Uncaught ReferenceError: Delete is not defined
    at HTMLImageElement.<anonymous> (Map.self-4f3676dc77ea2a47adb308e7e998bd6deaf8f6a9400070cbbaaf6412acd01e7c.js?body=1:162)
    at HTMLImageElement.handler (LeafletEnvironmentalLayers.self-bfc185ab0b58c254f69ba81d8a71d041a396d8e4ba15a90522dc0e1046225c5b.js?body=1:14320)
```

I believe it's due to this line:

https://github.com/publiclab/mapknitter/blob/f4733a544347916b0367647cf0545ad9b2869fa2/app/assets/javascripts/mapknitter/Map.js#L160-L168

Hi @sashadev-sky would you have a moment to take a look at this, do you think? I'm trying to get the latest cloud exporter code running in MapKnitter!

**Comment by sashadev-sky** [comment]
hi! pt2 of a GCI task is actually to upgrade leaflet to 0.8.7 in MK and implement the `replaceTool` method they added upstream, so I notified the contributor working on it that this change needs to be made too! I'm going to tag it as a GCI and note it in the PT2 of the original issue

**Comment by jywarren** [comment]
Oh awesome! Uh, i may have done the initial upgrade already in a PR just
now, apologies for overlapping with GCI. We can still merge both. And the
extra fix will be MUCH appreciated!

**Comment by sashadev-sky** [comment]
No problem!! The students PR for it is linked here: https://github.com/publiclab/mapknitter/pull/1127

**Comment by chen-robert** [comment]
@jywarren What page do you have to navigate to in order to get the error to appear? Just looking at the code, it appears to reference a variable `Delete` that doesn't seem to be defined anywhere else. 

We can probably fix this error by adding a `typeof Delete !== "undefined"` check before referencing the variable though.

**Comment by sashadev-sky** [comment]
@chen-robert so the toolbar is setup when you try to create a new map and then upload an image and click on it. Let me know if you need help figuring out how to get to that view! 

`Delete` was the name of `L.DeleteAction` in LDI at some point... lesson to myself about bad variable naming. Also note you'll want to rebase your PR 1st because your build is failing related to some thing that @jywarren fixed today

**Comment by jywarren** [comment]
Just viewing a newly created map, with 0.8.7 installed, i saw this error appear in the console. I may have added an image to the map already to get it to show! Hope this helps! I didn't find that anything was broken, but the error seems to indicate something was not hooked up right. Thanks!

**Comment by sashadev-sky** [comment]
closing this -- was resolved!
