### ISSUE TITLE
Login buttons don't work

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/mapknitter#1169]
When I am not logged in and I click 'Make a map', a dropdown shows up.
Then, I try to login via Google/Facebook/Twitter but they don't work.

On the other hand, when I click the "Log In" button on the navigation bar, it shows modal with buttons that do work.

[Demo](https://streamable.com/dg2ez)

URL: https://mapknitter.org/
Browser: Chrome 79
OS: Kubuntu 19.04

**Comment by Uzay-G** [comment]
Thanks for reporting this bug @VladimirMikulic! I checked and looked at the code base and I noticed that this is actually not a problem with the code because if you look at the [stable version of Mapknitter](http://mapknitter-stable.laboratoriopublico.org/#10/-11.9995/-77.0285/) everything works.

It must be an old change that just hasn't been merged yet.

**Comment by VladimirMikulic** [comment]
@Uzay-G Let's keep it open until the change is merged because mapknitter.org is the actual website that people visit. I doubt they'll search for branches :smile:

**Comment by Uzay-G** [comment]
Oh yeah I know :smile: @VladimirMikulic. I was just saying that they will push the changes soon :+1:

**Comment by VladimirMikulic** [comment]
Good to know, thanks @Uzay-G :)

**Comment by sakshi-2412** [comment]
@VladimirMikulic is this issue still there?

**Comment by VladimirMikulic** [comment]
No, it was resolved. Thanks @sakshi-2412.
