### ISSUE TITLE
maps not shown on PublicLab.org profile page

### ISSUE THREAD

**Issue by kcurrier** [publiclab/mapknitter#173]
When I create a map, leave mapknitter, and return to open my map, the map I created is not associated with my profile. I.e., in my profile, under the "MapKnitter Maps" tab it says "No MapKnitter Maps". I know the map exists, as I can search using its title and find it (and it is correctly attributed to my user name), but if I forget the title I don't have a good way to find the map again.

I've created two different Public Lab user names (asac177 & kapmappers) and had the same thing happen in both. 

Map created with user name asac177: title: "test", created on 5/1/2015
Map created with user name kapmappers: title: "Campus Point test", updated on 3/30/2015

Additional info:
-created maps on two different computers, one running Chrome (v. 42.0.2311.90) & Windows 7; the other also running Chrome (v?) & Win 7;
-URL you're on when you see the issue: http://publiclab.org/profile/asac177

**Comment by btbonval** [comment]
@kcurrier Thanks for the well written report!

@jywarren This ticket crosses mapknitter and plots2. The profile being pointed out is the MapKnitter tab on plots2. I'm a little curious how these two systems cross communicate so that this information would be available...

After searching it appears that this function is not implemented. That is completely understandable, it is not an easy problem to solve without a nice API call on the MapKnitter end and some AJAX on PublicLab.org to fill it out.

Traceback:
* https://github.com/publiclab/plots2/blob/b8cb16e7706a47302c799294a2f48702cb2f410b/app/views/users/profile.html.erb#L107
* https://github.com/publiclab/plots2/blob/be205c478337ddd1e58c90108a49b4cc171fca92/app/models/user.rb#L118-L126

We should remove the MapKnitter tab until there's code in place to retrieve the maps.

**Comment by btbonval** [comment]
@kcurrier Err sorry if that was a lot of detail. TL;DR: the feature is not implemented, so there probably should not be a visible mapknitter tab until the feature is implemented.

**Comment by kcurrier** [comment]
@btbonval Got it. Thanks for the quick response!

**Comment by jywarren** [comment]
We had that working but due most likely to my misunderstanding of how the RSS class works, it was causing outages -- i believe PublicLab.org was somehow just waiting up to 30 seconds for MK to respond to an RSS request... I don't think this would be a terribly hard fix but I haven't had a moment to look at it. 

Thanks for reporting!!

**Comment by btbonval** [comment]
Okay, I have broken this down into three tasks spanning two issues across two projects:

* https://github.com/publiclab/mapknitter/issues/175
* https://github.com/publiclab/plots2/issues/280

I'm going to close this ticket, but feel free to look at and/or follow those other tickets for more.
