### ISSUE TITLE
login/logout errors

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#224]
Logging in and out in Firefox 47 on Windows 8 requires going through the login process with "remember me" clicked, and then restarting the browser.  Otherwise I remain logged in or logged out.  
### PublicLab.org username

mathew

**Comment by jywarren** [comment]
Hi Mathew -- thanks for reporting. Just to confirm:

1. FF47/Win login works, but only when "remember me" is checked and browser
is closed and relaunched
2. Do you have to log in again once it's relaunched?
3. Were you logged into PublicLab.org before starting step 1?
4. Was anyone else logged into either PL or MK on this browser before you
started? Did they log out of both first?
5. Can you elaborate on "Otherwise I remain logged in or logged out." -- do
you mean that you have to restart the browser after logging out too? Would
you be able to describe that scenario separately, just to be sure it's
clear?

Thanks again!



On Thu, Jul 28, 2016 at 4:45 PM, mathew lippincott <notifications@github.com

**Comment by mathewlippincott** [comment]
_1. FF47/Win login works, but only when "remember me" is checked and browser is closed and relaunched_ 
exactly.  
_2. Do you have to log in again once it's relaunched?_
nope.  If "remember me" is un-checked, re-logging in has the same result (no apparent login)
 _3. Were you logged into PublicLab.org before starting step 1?_
no, but I was just able to repeat the bug while logged into Publclab.org
 _4. Was anyone else logged into either PL or MK on this browser before you started? Did they log out of both first?_
no, its my windows laptop, no other logins in the system.

 _5. Can you elaborate on "Otherwise I remain logged in or logged out." -- do you mean that you have to restart the browser after logging out too? Would you be able to describe that scenario separately, just to be sure it's clear? Thanks again!_

Yes, that's exactly right, if I click log out, I remain logged in until restarting the browser. 

thanks for looking into this.

**Comment by jywarren** [comment]
Can I ask you to try these steps in an incognito window to test if there is
a saved session issue involved?

Thanks.
