### ISSUE TITLE
Old Mapknitter maps not stitched 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#236]
### What happened just before the problem occurred
I went to check some maps that I had previously stitched with groups and it looks like they're not stitched anymore. Seems like the images are all piled up on eachother instead of the maps they once were. 

For example, all the maps associated with this project:
- https://publiclab.org/wiki/urban-waters-mapping-nola

### PublicLab.org username
Stevie

**Comment by jywarren** [comment]
Hi, stevie, thanks -- can you try it in an incognito window, and tell me what browser you were using? They don't all look perfect, but there are some that seem more or less all right:

![screenshot 2017-03-16 at 9 52 57 pm](https://cloud.githubusercontent.com/assets/24359/24025810/22367aba-0a93-11e7-8d5f-f2f4a5881390.png)

**Comment by steviepubliclab** [comment]
Hi Jeff,
I am looking at this on Chrome Version 56.0.2924.87. I see the same thing
in incognito. doesn't look like all the maps are wrong, but we had
previously stitched the ones that aren't showing up correct. I also think
that more maps are showing up correctly than last time I checked it.
-Stevie

**Comment by jywarren** [comment]
Hi, can you screenshot one or two that look wrong to you? It may be that
they were vandalized, and that there is no bug. Is that a possibility? Do
you have any exported images or documentation of what they looked like
before?

If they were vandalized, it may not have been intentional and I'd even say
probably wasn't. But it's irreversible as far as I know. This may be a good
reason to propose a better locking system or perhaps a version tracking
system so you could revert it.

**Comment by steviepubliclab** [comment]
Hi, thanks for bumping this up. I check the maps I had mentioned in this thread and they seem ok now. Can close.

Thank you!
