### ISSUE TITLE
images not showing up on image tab

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#257]
### What happened just before the problem occurred
I was hoping to delete one of the images I uploaded. Since I'm not currently able to see the toolbar, I went to the image tab and tried to delete it from there, but I'm not able to see the images I've uploaded on the image tab right now: 

<img width="983" alt="screen shot 2018-04-27 at 11 17 56 am" src="https://user-images.githubusercontent.com/7490478/39373311-cdf4971a-4a0c-11e8-9b68-ea2a3d14255d.png">

I'm working in chrome

**Comment by steviepubliclab** [comment]
I found out if you refresh the page the images will show up and the toolbar will work.

**Comment by gauravano** [comment]
Hi @steviepubliclab, thanks for reporting. I will update the issue details soon. If anyone want to inspect the issue, feel free to add details. Thanks!

**Comment by sashadev-sky** [comment]
This issue has been reported in the past but I closed them all because they were from years ago. Linking them here because the issue described is the same:  

- #226 (on Chrome Version 52.0.2743.116 (64-bit) Mac OS 10.11.6) 

- #179 (on Browsers: Firefox 38.0.1, Chrome 43.0.2357.81). Also reports that it has to do with the state of not having any images already because refresh resolves the problem but if the images are deleted it comes back.

**Comment by sashadev-sky** [comment]
Also linking #154

**Comment by gauravano** [comment]
Solved in #562. Thanks!
