### ISSUE TITLE
Request issues related to integer coordinates on LEL map

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#276]
@sagarpreet-chadha - people are LOVING the new layers. I wanted to note that it looks like youre truncating the lat/lon to an integer and thus getting no results when zoomed in too far:

https://mapknitter.org/map/region/Gulf-Coast.json?minlon=-71&minlat=41&maxlon=-71&maxlat=41

Also, this link seems not to be responding? https://sagarpreet-chadha.github.io/FractrackerCSV.json

I think the integer bug may affect other layers too: 

https://alerts.skytruth.org/json?n=100&l=41,-72,41,-70

**Comment by jywarren** [comment]
So to be clear, i think it's requesting data between latitude 41 and 41, so range of zero. @sagarpreet-chadha maybe you could just have an extra comparison to ensure there's a minimum requested width...

**Comment by sagarpreet-chadha** [comment]
`var northeast = self._map.getBounds().getNorthEast() , southwest = self._map.getBounds().getSouthWest() ;`

AND

`var MapKnitter_url = "https://mapknitter.org/map/region/Gulf-Coast.json?minlon="+parseInt(southwest.lng)+"&minlat="+parseInt(southwest.lat)+"&maxlon="+parseInt(northeast.lng)+"&maxlat="+parseInt(northeast.lat);`

It is happening because i am using `parseInt`  AND when we super zoom --> truncated southwest and northeast coordinates merges ...opening a new PR in. LEL .

**Comment by sagarpreet-chadha** [comment]
PR: https://github.com/publiclab/leaflet-environmental-layers/pull/48
