### ISSUE TITLE
Reduce Ruby warnings in recent builds

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#345]
We're looking at upgrading Ruby in #319 and i'm seeing a lot of warning messages that weren't previously there in the recent #341 PR, which make it hard to read the output:

https://travis-ci.org/publiclab/mapknitter/builds/494340774

@sashadev-sky @gauravano @SidharthBansal what do you think, is this just stricter behavior from a more recent version of Ruby, or what else can we do to reduce the # of warnings? Thank you!

Just to note, it's not just in #341, i guess; this recent `main` branch build has lots too:

https://travis-ci.org/publiclab/mapknitter/builds/493792946

**Comment by jywarren** [comment]
Looks like we're in Ruby 2.1.x in all these, so dunno if it's related to newer ruby versions. Errors sampling:

```
/usr/local/lib/ruby/gems/2.1.0/gems/will_paginate-3.1.6/lib/will_paginate/railtie.rb:1: warning: loading in progress, circular require considered harmful - /usr/local/lib/ruby/gems/2.1.0/gems/will_paginate-3.1.6/lib/will_paginate.rb

/usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.22.5/lib/rails/application.rb:98: warning: File.exists? is a deprecated name, use File.exist? instead

/usr/local/lib/ruby/gems/2.1.0/gems/will_paginate-3.1.6/lib/will_paginate/core_ext.rb:8: warning: previous definition of except was here
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/hash/except.rb:19: warning: method redefined; discarding old except!

/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251: warning: loading in progress, circular require considered harmful - /usr/local/lib/ruby/gems/2.1.0/gems/ruby-openid-2.7.0/lib/openid.rb
	from /usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:5:in  `<main>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:5:in  `select'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:17:in  `block in <main>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:17:in  `require'
	from /app/test/unit/comment_test.rb:1:in  `<top (required)>'
	from /app/test/unit/comment_test.rb:1:in  `require'
	from /app/test/test_helper.rb:2:in  `<top (required)>'
	from /app/test/test_helper.rb:2:in  `require'
	from /app/config/environment.rb:5:in  `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in  `method_missing'

```

Hm, also looking back a ways, this didn't have the errors but is actually ruby 2.1.2 also: https://travis-ci.org/publiclab/mapknitter/builds/410929149

**Comment by gauravano** [comment]
Going through a quick look at the above build logs point to deprecated `File.exists?` as a cause of these warnings, I will see if the #320 throws the same warning or not. Thanks!

**Comment by sashadev-sky** [comment]
@gauravano @jywarren I will get involved with this too during mysql upgrade. If they are simple fixes I can always update them in that PR

**Comment by sashadev-sky** [comment]
Copying over some information from my PRs #380 and #355  related to this:
- `Warning ::Fixnum is deprecated error`: this warning will be fixed with an update to **Rails 5**. [see here](https://stackoverflow.com/questions/41463999/warning-constant-fixnum-is-deprecated-when-generating-new-model/42336144)
- `File.exists?` (deprecated since ruby 2.2.0) updated to File.exist? comes from gems and from the source code for running a rake test. Source code is updated to File.exist? for **Rails 4**.

**Problem gems:** 
- `paperclip` seems to cause the greatest number of errors including errors mentioned above
   - Dependabot recommended update to 4.3.7 confirming this update is compatible but does not get rid of any warnings. 
   - Recommended solution is to wait for upgrade to **Rails 5.2** and then migrate away from Paperclip as its been deprecated: [see here](https://thoughtbot.com/blog/closing-the-trombone)
- `ruby-openid`
  - updating to latest version does not get rid of errors but I see a PR open on the gem page that would fix some of the warnings currently receiving (unused parameters, file.exists?)
- `open_id_authentication`

- `will_paginate`
  - already updated but PR currently open on the gem page to get rid of circular warnings error

- `friendly_id`
  -  Updated versions removed support for **Rails < 4.0**. [see here](https://www.rubydoc.info/github/norman/friendly_id/file/Changelog.md) so maybe try catching up to Rails 4.0 first

**Comment by sashadev-sky** [comment]
@jywarren from my comment above, should I open a PR to update to Rails 4 next to try to resolve some of the `File.exists` and maybe `friendly_id` errors?

**Comment by jywarren** [comment]
sure! Thank you!!!

**Comment by kaunair** [comment]
@sashadev-sky  Sure that will be awesome.
Thanks!

**Comment by alaxalves** [comment]
A lot of those warnings will be missing in Rails Upgrade. I empirically upgraded to Rails 4.2.8 [here](https://github.com/alaxalves/mapknitter/tree/rails4) and a lot of those warning have gone missing.

**Comment by jywarren** [comment]
:-) awesome!!!

**Comment by sashadev-sky** [comment]
@alaxalves Thank you that is great to hear! I'm going to open an issue regarding upgrading to Rails 4.0 to take it one step at a time. I will tag you there, let me know if you remember any gems or custom configs you remember having to update.

**Comment by alaxalves** [comment]
@sashadev-sky The greatest approach to this is gradually updating versions, such as 3.2 to the next release. *eg. rails 3.2 to rails 3.3*. using the appropriate rake task. I'll try to make all those steps clearer in my GSoC proposal. I'll finish it today(04/03/2019) and I submit the link here. What do you think?

**Comment by jywarren** [comment]
I think we're doing MUCH better here now, and can close up and focus on Rails upgrades!!!

**Comment by jywarren** [comment]
https://travis-ci.org/publiclab/mapknitter/builds/520554195

**Comment by jywarren** [comment]
Thanks, everyone!
