### ISSUE TITLE
Can not Delete anonymous post

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#445]
### What happened just before the problem occurred
No able to delete the anonymous post.
### Relevant URLs

https://

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
I think only moderators and admins have that privilege.

**Comment by avsingh999** [comment]
@gauravano But if we create map mistakenly then no option for delete. Is there any option for delete except admin.
thanks

**Comment by gauravano** [comment]
As while creating a map anonymously, no data is stored so can't allow any user to delete that post. Although, we can think of a flag system or moderation system. What do you think @jywarren?

**Comment by kaunair** [comment]
Can someone tell me why we have anonymous users? I understand it's for privacy reasons, but privacy for whom exactly?
Does the user want to avoid sharing personal details with other users, or does he want to avoid sharing details with the platform itself?

**Comment by sashadev-sky** [comment]
I still think this one is an important problem! I cannot even say how many maps I have made labeled "test", that I will also never be able to find again because there are 60 pages for results "test"

@kaustubh-nair I guess we have anonymous posts because having to make an account might deter a user from making a map, just out of inconvenience. 

@jywarren @gauravano I think we should do a review of the maps anonymous users make and those made by people with accounts, to see if there is a consistent difference in quality / effort. I think there will be. Maybe what would be a good idea is you can make a map anonymously, and export it, but you cannot post the map to the site to save it unless you login.

We can add a you must login to post this map notice under you must login to comment.

**Comment by jywarren** [comment]
We have had input from community partners that people who may be vulnerable or are concerned about being connected to data produced on MapKnitter.org may be more comfortable producing maps anonymously, despite the drawbacks. So we have continued to allow this although we are getting better at explaining why it presents difficulties like this one, and trying to help people make a good decision about whether to use an anonymous map or not. Thanks! 

Happy to leave this open for discussion if you want! Perhaps if you want to leave it open, you could change the title to something like "discussion of anonymous features" or something? Thanks!

**Comment by sashadev-sky** [comment]
@jywarren I am going to delete this issue, and open up a new issue titled "add wiki documentation on anonymous editing and why we allow it" or something

**Comment by SidharthBansal** [comment]
Cool

**Comment by jywarren** [comment]
awesome!
