### ISSUE TITLE
Integrate Rubocop with Travis

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#548]
It could be very useful having rubocop implemented along with Travis pipelines. This would enforce what @kaustubh-nair suggested [here](https://github.com/publiclab/mapknitter/pull/547#issuecomment-484629635).

### Relevant URLs

I have implemented this same thing in:
https://gitlab.com/klara-org/klara-api/blob/master/.gitlab-ci.yml#L44
https://gitlab.com/noosfero/noosfero/blob/master/.gitlab-ci.yml#L144
https://github.com/falko-org/Falko-API/blob/devel/.travis.yml#L34

### PublicLab.org username

@alaxalves

**Comment by alaxalves** [comment]
@kaustubh-nair @icarito @jywarren I could take advantage of my Rubocop Config related PR and solve this already too. What yall think?

**Comment by kaustubh-nair** [comment]
Sounds interesting.. But I'm unsure how this is different from code climate running rubocop?

**Comment by alaxalves** [comment]
> Sounds interesting.. But I'm unsure how this is different from code climate running rubocop?

The travis build would break if Rubocop linting issues don't get solved. This would encourage developers to follow our Rubocop stylesheet if they want their PRs merged.

**Comment by kaustubh-nair** [comment]
Yes this can be a good way to encourage the style guide, but in my opinion we should keep Travis separate from Rubocop since it can get a bit oppressive at times. This might get a little demotivating ( especially for newcomers) if we have such a strict enforcement. I believe Rubocop offenses can be ignored sometimes if it is not a major offense. In such a case where we want to ignore the offences, we cannot test on Travis because it will break due to Rubocop.
Anyway, this is my personal opinion.. let's see what @jywarren thinks.

**Comment by kaustubh-nair** [comment]
@publiclab/mapknitter-reviewers Please provide your inputs about this here

**Comment by cesswairimu** [comment]
Thanks @kaustubh-nair for linking me to this. I am for just having travis running the tests and builds. Because in my mind when travis break I am like "I really broke something" and we have codeclimate that runs rubocop and even gives suggestions for fixes.
