### ISSUE TITLE
Error in creating new map

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#700]
**Description**

After fetching the latest commits, I got the following error on creating a new map.

![Selection_183](https://user-images.githubusercontent.com/32747809/59515554-025bd480-8edd-11e9-8436-6bc1a8e1c3f8.png)

**Comment by divyabaid16** [comment]
Hi @cesswairimu maybe you can help here.
Thanks!

**Comment by cesswairimu** [comment]
Hi @divyabaid16 sure taking a look

**Comment by cesswairimu** [comment]
Unfortunately I can not replicate this locally..its creating a map fine on my end. Just making sure did  you run `bundle install` after pulling? Also if you could share the error displayed on the terminal logs maybe I can get more info to help/debug. Also anyone else getting this? Thanks

**Comment by divyabaid16** [comment]
Ahh, it was working fine for me today.
Sorry for bothering you @cesswairimu .

**Comment by cesswairimu** [comment]
cool, @divyabaid16, I am having the problem creating a map now(not the same error)+ the map is not being rendered in `maps/new`   If you have a minute, could you please pull the lastest code and let me know if you can successfully create a map...You might want to run `yarn install` since we have changed from bower to yarn. Thanks

**Comment by divyabaid16** [comment]
@cesswairimu, it is working for me.

**Comment by cesswairimu** [comment]
Okay maybe I am missing something. Thanks
