### ISSUE TITLE
Adding map doesn't automatically populate the lat and long coordinates or the url.  Map also doesn't show if information is entered manually

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/mapknitter#728]
![image](https://user-images.githubusercontent.com/29240939/59781648-3b53ca80-928a-11e9-8535-269144a4eb82.png)

If information is entered manually, it seems to create the map but doesn't show the map at all.
@divyabaid16 I'll start working on this.

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by divyabaid16** [comment]
Thank you @rarrunategu1 for opening this issue and starting to work on this. I was also facing this for a few times.

**Comment by cesswairimu** [comment]
Thanks for opening this, I am also experiencing the same.Plus the world map is not rendered on the maps/new template. Mentioning @kaustubh-nair who might have some pointers, it seems this first occurred after we changed from bower to yarn.

**Comment by kaustubh-nair** [comment]
Is this happening only on `unstable`?
I tried this on `main` and it seems to work fine?

**Comment by divyabaid16** [comment]
It is working fine on main @kaustubh-nair .

**Comment by cesswairimu** [comment]
oh, I am having the prob locally on main

**Comment by kaustubh-nair** [comment]
Any idea what package we're using for this? @cesswairimu @divyabaid16 @rarrunategu1 
I couldn't find anything in error logs
It's possible some package isn't being loaded correctly.

**Comment by cesswairimu** [comment]
I think its google maps api

**Comment by rarrunategu1** [comment]
I've been looking at the package.json and it still has some bower dependency in it.

prototypejs-bower": "plynchnlm/prototypejs-bower#1.7.2  

Should that not be changed?  I'm looking into how that would be changed if we're using yarn instead.

**Comment by jywarren** [comment]
`prototypejs-bower` is a very very old library, adapted to work with bower, which we don't use anymore... i hope we can drop prototypejs! But... indeed it seems like a variety of issues may have come up due to the Yarn switchover. Can folks share their JavaScript console logs when they start typing in the "title" field? It's supposed to:

1. make the title lowercase
2. replace spaces with hyphens
3. splice out punctuation
4. copy the result into the map URL

The HTML is here:

https://github.com/publiclab/mapknitter/blob/fd7c3a2cd79ab8c3fdf2b19d28945e535993cbd7/app/views/maps/new.html.erb#L13-L31

Aha - and the JavaScript is here:

https://github.com/publiclab/mapknitter/blob/fd7c3a2cd79ab8c3fdf2b19d28945e535993cbd7/app/views/maps/new.html.erb#L86-L94

It looks like it was depending on the `id`s of `#map_slug` and `#map_name`, but those have changed in the Bootstrap upgrade? This should start working again if we re-add those `id`s to the inputs above. 

As to the world map, maybe we need another issue open with more documentation of what's happening?

**Comment by rarrunategu1** [comment]
Yarn install now shows these errors which explain why it might not be working.

warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "leaflet-environmental-layers > leaflet-spin@1.1.0" has incorrect peer dependency "leaflet@^0.7.3".
warning " > leaflet-illustrate@0.0.2" has unmet peer dependency "grunt-cli@0.1.13".
warning " > leaflet-spin@1.0.0" has incorrect peer dependency "leaflet@^0.7.3".

**Comment by rarrunategu1** [comment]
When you remove the document.ready it works.  But I need to figure out why it's not working with it.

**Comment by jywarren** [comment]
Hmm. document.ready is a bit odd, if it's run after the page is loaded,
then it'll miss that event and never trigger.

**Comment by rarrunategu1** [comment]
The page is not being loaded correctly.  I am receiving these errors when I inspect the page.
![image](https://user-images.githubusercontent.com/29240939/59936432-fc567e00-941d-11e9-94dc-47a441d66854.png)
![image](https://user-images.githubusercontent.com/29240939/59936485-185a1f80-941e-11e9-8b02-df15d8e41ff4.png)
![image](https://user-images.githubusercontent.com/29240939/59936515-34f65780-941e-11e9-93fa-b4663ac06020.png)

After looking up the first error it may be a matter of the scripts not loading in correct order.  I'm trying to see which html document is attached to this.  Is it https://github.com/publiclab/mapknitter/blob/6d8d8b5b3f6a8dfd8415f3a70efbeccefc73f044/app/views/map/_leaflet.html.erb
or this?
https://github.com/publiclab/mapknitter/blob/6d8d8b5b3f6a8dfd8415f3a70efbeccefc73f044/app/views/map/leaflet.html.erb
@gauravano @kaustubh-nair @divyabaid16 Can someone help me clarify what html document is trying to load when you create a new map?  I thought it would be in app/views/maps/new.html.erb but there are no scripts src's loading there.

**Comment by jywarren** [comment]
Ah, good catch -- once the page says it's done loading, what happens when
you type `L` in the JS console and hit return? You should see Leaflet, but
if not, perhaps Leaflet is not itself loaded at all? Otherwise it's
probably what you're saying about ordering.

The other possibility is that now we're on Yarn, you need to re-install
dependencies using Yarn instead of Bower? have you run `yarn install` since
the change (a few days ago?) Maybe @kaustubh-nair can offer help - was this
change documented in the README?

**Comment by kaustubh-nair** [comment]
Hi @rarrunategu1 I can look into this if you're stuck!
@jywarren Yes. Readme was updated in an FTO I made for it. https://github.com/publiclab/mapknitter/pull/718/files

**Comment by rarrunategu1** [comment]
hello @kaustubh-nair, I re-installed yarn globally per the instruction and installed yarn again with yarn install --force.  This is what I get.  It looks fine except for some warnings.
![image](https://user-images.githubusercontent.com/29240939/59944671-5c0b5400-9433-11e9-8340-5d7764388793.png) but when I try to run the application again I still get the same errors.  Is there something I'm missing?

**Comment by kaustubh-nair** [comment]
Hi all
I've submitted a patch for this issue, but there is another problem of the annotation files not loading
If someone could help out with that, it could be great https://github.com/publiclab/mapknitter/issues/734
Thanks!
