### ISSUE TITLE
Weekly community Check-In #29 - Keep Reinventing

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/mapknitter#851]
Hi everybody :smiley: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

**This Week's Theme:**

**Keep Reinventing:** Reinventing is the key to build something successful out of the existing.
This week share something you have reinvented to make it successful. It could even be an existing feature you worked upon to make it better.

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) 

## Note to Summer of Code interns:

Hi, we request all the SoC students to include the below-mentioned points in their check-in comment:
- FTOs created in the previous week
- Progress for your project
- Upcoming week's goals 
- PR reviewed by you in the previous week
- Work completed last week.
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible. 
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.

Thank you!

**Comment by ViditChitkara** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @pdurbin @HarshKhandeparkar @niravasher

**Comment by ViditChitkara** [comment]
@aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @michelelong @cryptoclidus @mohamed-elalem @konolga

**Comment by alaxalves** [comment]
Hey guys,
Currently I'm helping to reinvent a lot of things on Mapknitter :smile: :smile: :smile:. Since I'm working on rails upgrade and such, I've been busy reinventing the entire code to newer patterns. But right now I've been working on reinventing Jenkins setup for Mapknitter's unstable.

**FTO's created:**

- https://github.com/publiclab/mapknitter/issues/850

**Progress for your project:**

My and Kaustubh are pretty ahead on our work, I've made the ruby upgrade(since rails 6 needs >2.5) and upgraded a few portion of code in https://github.com/publiclab/mapknitter/pull/824. Kaustubh has taken this on while I'm working on the Jenkins thing I mentioned.
So far I have improved a bunch of the Jenkins setup and I'm pushing it to unstable branch. I'll notify everyone on Gitter when its ready. All of this Jenkins stuff popped up when I tried to push Rails 5.2.3 to unstable, since it was working on local env but not on unstable.

**Upcoming week's goals:**

Bulk Jenkins up :smile:, finish patching Rails 5.2.3 upcoming bugs and push Rails 6 to unstable. Maybe get Rails 5 on main??

**PR reviewed by you in the previous week**

- https://github.com/publiclab/mapknitter/pull/837
- https://github.com/publiclab/mapknitter/pull/852
- https://github.com/publiclab/mapknitter/pull/805

**Work completed last week.**

Merged Rails 5 into development branch and pushing it to unstable.

- https://github.com/publiclab/mapknitter/pull/669

**What things you did collaboratively last week? This is really important we want team spirit.**
Rails 6 upgrade along with @kaustubh-nair, and I have opened my first FTO issue.

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/community-toolbox/issues/237. Thanks all

**Comment by gauravano** [comment]
Reinventing is a great word with a lot of meanings. It could be doing something new using existing technology or maybe doing something better. How I started seeing it is - building something better using existing methods, but with the efficiency in mind. 

I think, considering edge cases, tests, complexity, etc for each PR makes it a nice adventure. And, learning new thing never bores you. So, maintain the balance of both. I tried it in https://github.com/publiclab/plots2/pull/4439 last.
