### ISSUE TITLE
spam map descriptions

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#9]
![screen shot 2014-07-01 at 4 49 48 pm](https://cloud.githubusercontent.com/assets/1203280/3450383/7f936bac-017a-11e4-9784-36956bb2e4f3.png)

Not map related comments, such as:
comment6, premature ejaculation gp, kaysnd, premature ejaculation ginseng, %]]], cheap viagra next day delivery, 0826, premature ejaculation hypnosis download, gznkyj, cheap viagra new zealand, zuflij, cheap viagra online usa, 6620, premature ejaculation prevention tips, 14979, premature ejaculation percentage, 8-]], premature ejaculation homeopathy treatment, 48420, premature ejaculation patient co uk, iicye, premature ejaculation information, ezvp, cheap viagra levitra cialis, lqhqt, premature ejaculation in teenagers, 36541, cheap viagra melbourne, 8-P, premature ejaculation medicine in india, jclu, cheap natural viagra, zel, premature ejaculation in men over 50, 516381, premature ejaculation lloyds pharmacy, %[[[,

**Comment by ebarry** [comment]
Bringing this issue back up because in December 2015 Hagit pointed out to me that all her pre-2014 Jerusalem maps have vandalized descriptions, as do many of the Gowanus maps. 

If it is currently the case that we have "Disallowed anonymous or non-logged-in edits of description and location for maps which were created by a non-anonymous/logged-in user" working on mapknitter, can we look forward and think about how to allow owners to lock their maps so that no one other than them can edit the location and description?

**Comment by jywarren** [comment]
>  how to allow owners to lock their maps so that no one other than them can edit the location and description

This is automatically the case. After the changes made as of Dec 23 2014, any map that has an owner cannot have its description or location edited by non-owner. 

Can you link to the maps you're referring to? Are the maps owned, or anonymous? If anonymous, would you like to request we (as admins) make the maps owned, and by whom?

**Comment by ebarry** [comment]
Here's an example of a map i (or someone in GLAM) made but apparently specified as "anonymous" that has been vandalized: https://mapknitter.org/maps/2012-12-25-gowanus-canal-hurricane-sandy-survey

I guess i should go through Gowanus maps and claim any that are anonymous and request them to be transferred to me or another mapknitter steward account?

**Comment by jywarren** [comment]
Yes, as any anonymous map has no owner, so we cannot lock them. Thanks!

**Comment by ebarry** [comment]
I believe that these are my maps: 
https://mapknitter.org/maps/union-square
https://mapknitter.org/maps/2011-08-06-brooklyn-newtowncreek
https://mapknitter.org/maps/2011-7-31-brooklyn-gowanus-ir
https://mapknitter.org/maps/2011-11-19-brooklyn-gowanus
https://mapknitter.org/maps/test-20120928-washpark
https://mapknitter.org/maps/2012-09-28-nyc-washsquarepark-parsons
https://mapknitter.org/maps/2012-08-21-nyc-bronx-soundviewoysterreef-orrp
https://mapknitter.org/maps/2012-12-20-gowanus-canal-post-sandy-sewage
https://mapknitter.org/maps/2012-10-20-gowanus-gcc-treegiveaway

These belong to Jen Hudon: 
https://mapknitter.org/maps/jennifer-hudon
https://mapknitter.org/maps/unionsquarejenn
https://mapknitter.org/maps/jennunionsquare

Most if not all of the remaining Union Square maps that are on the first page of results when you click the regional link to maps in the New York/New Jersey region that have people's names in the titles were either made by my students or by folks who attended the workshop i held in Union Square. These have spam in the descriptions but i don't see how we can get in touch with folks to claim them all. Any ideas?

**Comment by jywarren** [comment]
Yes, you can look up their emails by username on PublicLab.org, no?

Or, its possible that admins can edit these fields, and since they are not
anonymous maps, they won't be vandalized again (I.e. the vandalizing
predates the fix). Can you try?

Or are you not an admin in Mapknitter and we should make you one?
